### PR TITLE
Deprecating image and spectrum as registry servicetype-s

### PR DESCRIPTION
**Pull request by msdemlei**
I'm also promising all-VO-searches in some other way in the docs (which perhaps I shouldn't).

This is supposed to address bug #429.

### CODE REVIEW

**Comment by bsipocz** [comment]
I would not like to go ahead with this deprecation, until we have a good/convenient alternative. I totally see the problems, but OTOH, the users should not really need to know about the versions, so doing an `'image` regsearch should really just return both SIAv1 and v2. Then they can be used individually (assuming the search() functionality is fixed for sia2). 

E.g. I strongly feel instead of this, one should be able to do one `image` search, that returns the ~90 services. 

```
import pyvo
image_services_v1 = pyvo.regsearch(servicetype='sia')
image_services_v2 = pyvo.regsearch(servicetype='sia2')
v2_irsa = [s for s in image_services_v2 if 'irsa' in s.ivoid]
v1_irsa = [s for s in image_services_v1 if 'irsa' in s.ivoid]
```

The user should do a lot of digging after that anyway to see e.g. which "Spitzer" they want, but otherwise all the entries look so similar, that they should be in one result.

```
In [27]: v1_irsa[0]
Out[27]: ('ivo://irsa.ipac/2mass/images/asky-at', 'vs:catalogservice', '2MASS ASKY AT', '2MASS All-Sky Atlas Image Service', 'research', 'This service provides access to and information about the 2MASS All-Sky Atlas Images. Atlas Images delivered by this service are in FITS format and contain full WCS information in their headers. Additionally, the image headers contain photometric zero point information. 2MASS Atlas Images are suitable for quantitative photometric measurements.', 'https://irsa.ipac.caltech.edu/applications/2MASS/IM', '', 'archive', '', '', np.float32(nan), 'infrared', ['https://irsa.ipac.caltech.edu/cgi-bin/2MASS/IM/nph-im_sia?type=at&ds=asky&'], ['ivo://ivoa.net/std/sia'], ['vs:paramhttp'], ['std'])

In [28]: v1_irsa[1]
Out[28]: ('ivo://irsa.ipac/2mass/images/asky-ql', 'vs:catalogservice', '2MASS QL', '2MASS All-Sky Quicklook Image Service', 'research', 'This service provides access to and information about the 2MASS All-Sky Quicklook Images. The Quicklook Images delivered by this service are restored from lossy-compressed files in FITS format with full WCS information contained in the image headers. These images are suitable for position measurements, finding charts and visual inspection of the near-infrared sky.', 'https://irsa.ipac.caltech.edu/applications/2MASS/IM', '', 'archive', '', '', np.float32(nan), 'infrared', ['https://irsa.ipac.caltech.edu/cgi-bin/2MASS/IM/nph-im_sia?type=ql&ds=asky&'], ['ivo://ivoa.net/std/sia'], ['vs:paramhttp'], ['std'])
```

**Comment by trjaffe** [comment]
The NAVO Python working group has discussed this PR internally and come up with a review. (TJ is just speaking for the team.) 

Basically, we agree that while we work on the alternative (we also have a review of #470), the user needs to be warned that they are not getting global discovery results. We just feel that a deprecation that involves removing mention of "image" and "spectrum" from the docs is not yet appropriate, so we would suggest two things.  Firstly, can the short warning link to the docs? I.e., something like:   

> “Warning: services of type “image” are not complete.  See https://pyvo.readthedocs.io/en/latest/api/pyvo.registry.Servicetype.html#pyvo.registry.Servicetype.”  

Then in the updated doc page, we suggest not yet removing mention of the "image" and "spectrum" options but adding something like:  

> “Contrary to appearances, querying “image” or "spectrum" services will not get you all resources serving those data products through the VO.  Ensuring you get a more-or-less complete list of what’s available would require you to become a bit more familiar with the  complexities of the VO. You would, for instance, have to search for images served three different ways: SIA, SIAv2, and ObsTAP, each  of which has a different interface. This “image” search currently only searches for the first of those types, and "spectrum" similarly omits ObsTAP.  A  global discovery module is under active development to provide this functionality. When it is ready, these two misleading options will be deprecated.” 

This gets the warning out there, gives a pointer to the intrepid user who wants to dig in, and promises a better way.

**Comment by msdemlei** [comment]
Thanks for the review and the suggestions!

On Tue, Jul 16, 2024 at 06:44:59AM -0700, trjaffe wrote:
> deprecation that involves removing mention of "image" and
> "spectrum" from the docs is not yet appropriate, so we would

I was not quite sure whether it is the deprecation as such that you
do not like or just the lack of an explanation; since you say:

> suggest two things.  Firstly, can the short warning link to the
> docs? I.e., something like:

and hence would raise a warning anyway, it would seem you are ok with
the DeprecationWarning, though; I also can't think of a more
appropriate warning, because what we tell people effectively is:
Don't use that, we don't like it, and we hope that one day we can
drop it.

So... I've reworked the message and explain the rationale of the
deprecation in a few more words, and I have folded things into one
commit, 17681b608.

Can you live with that?

**Comment by msdemlei** [comment]
Ummm... it's actually commit 3bb54e57.   Ahhh... Can we have a plan to change the SIA2 tests so running the test suite locally before a commit becomes non-tedious again?

**Comment by trjaffe** [comment]
This is fine with me.  But it's @bsipocz who has the opinions on how to use astropy's deprecation warning.  Brigitta, is there a different type of warning you prefer this uses?

**Comment by bsipocz** [comment]
I have issues with the alternative as it requires the users to know way more about SIA, SSA, etc.

So let me phrase it differently: are we ready to remove all usage of 'image' in the Navo material? If it's just a heads up warning (e.g. userwarning type) then it's fine not to and say something about it during the session, but we definitely should use something that raises a deprecation as that already marks the functionality for removal.

**Comment by trjaffe** [comment]
> I have issues with the alternative as it requires the users to know way more about SIA, SSA, etc.
> 
> So let me phrase it differently: are we ready to remove all usage of 'image' in the Navo material? If it's just a heads up warning (e.g. userwarning type) then it's fine not to and say something about it during the session, but we definitely should use something that raises a deprecation as that already marks the functionality for removal.

We are not ready yet.  So right now, it's a heads up.  But we will be working on getting rid of our usage of it.

**Comment by msdemlei** [comment]
On Fri, Jul 19, 2024 at 09:26:14AM -0700, Brigitta Sipőcz wrote:
> I have issues with the alternative as it requires the users to know
> way more about SIA, SSA, etc.

Let me say again that I don't think the servicetype constraint ought
be be considered API that normal users would routinely use.  It does
make sense for certain maintenance jobs on the side of "VO
engineers".  That is leaked out to "normal" users was more of a
kludge that somewhat worked in the early days of the VO.  These days,
"normal" people should do data discovery (i.e., without constraining
the access mode) and then use the most capable interface they see in
access_modes().

> So let me phrase it differently: are we ready to remove all usage
> of 'image' in the Navo material? If it's just a heads up warning

You should be: As I said, there is no way I can see to make this work
in a way that is not totally confusing.

If there is stuff you do with servicetype constraints that does not
work without the servicetype constraint (and I suspect that is the
case until we get productTypeServed with the next VODataService), I
am *all* for honesty and sprinkling in sia or sia2 with an
appropriate warning.  That warning you need anyway when saying
"image" right now, as it raises entirely unrealistic expectations.

> that raises a deprecation as that already marks the functionality
> for removal.

I am convinced this is exactly what we should do: There is no
non-confusing functionality we could give "image" or "spectrum" in
servicetype.  What these words promise is positively complex and
beyond anything a normal user could write on top of registry alone;
see add-global-discovery, building a special API for what these
should do, for why I'm saying that.

**Comment by msdemlei** [comment]
On Fri, Jul 19, 2024 at 09:31:48AM -0700, trjaffe wrote:
> > So let me phrase it differently: are we ready to remove all usage
> > of 'image' in the Navo material? If it's just a heads up warning
>
> We are not ready yet.  So right now, it's a heads up.  But we will
> be working on getting rid of our usage of it.

Hm... is this a blocker for merging the Deprecation into 1.6?

If so, I'd plead again that blindly search-replacing "sia" where
there is "image" now would actually be an improvement.

It even, I claim, requires fewer words of explanation: "'sia' is one
of the image discovery protocols that the VO define, and here we
assume we know which one to pick." vs. "Regrettably, writing 'image'
here does not mean we will be finding all image services.  For
historical reasons, it actually means 'find all SIA 1 services',
which..."  I am happy I don't have to fill in the ellipis :-)

**Comment by bsipocz** [comment]
While I was looking into updating the navo material to switch out all the `image` and `spectrum` examples, I notice that we do have `sia2` but don't have `sia1` (only `sia`). 
I see that we cannot get rid of `sia` as is to mean `sia1`, but nevertheless I think it would be better to add the more explicit `sia1` and use that when teaching.

Do you think it fits into this PR, or should I rather open a follow-up to this one?

**Comment by msdemlei** [comment]
On Tue, Jul 30, 2024 at 12:13:10PM -0700, Brigitta Sipőcz wrote:
> Do you think it fits into this PR, or should I rather open a
> follow-up to this one?

I agree, and I think that's exactly on-topic for this PR. I'm on
holiday until next Wednesday, though.  If anyone else wants to push
the relevant changes (I think there are not many, except that we
should decide on what we intend to do with "sia" [my hunch: Keep it
as a synonym for sia1; we will have similar cases in the future, when
there are new major versions of standards]), that's fine, otherwise
I'll propose some changes in a week.

**Comment by msdemlei** [comment]
On Thu, Aug 01, 2024 at 11:11:52AM -0700, Brigitta Sipőcz wrote:
> Looking at the SIA classes, we kept the without number ones as
> SIAv1, so keeping `sia`  is fine. In fact, we haven't introduced
> `SIA1...` classnames, but here I still think it would be useful for
> removing ambiguity.

My take: Let's not.  I'm extremely skeptical about breaking changes
for reasons of good taste (so let's not *rename* the classes), and
having multiple names for the same thing requires a lot of
explanation and is still confusing, so it's probably not a win from
an asthetic point of view (so let's not *add aliases*).

Anyway, with the latest push you can say "sia1", and the failing
tests are unrelated to this code.  What's not *overly* pretty is that
und access modes, the thing will still be called "sia" (because
that's the IVOA short name).  How bad do we think this is?  Me, I'd
rather strongly prefer to not add any cosmetic hacks in the describe
method, and even less in access_modes and friends.

**Comment by bsipocz** [comment]
OK, I'm totally fine with leaving the classes, and only have this `servicetype` 'sia1' alias. We may still want to add more explicit docstrings, but that is way out of scope for this PR.

**Review by bsipocz — APPROVED** [review]
I think this can go in now once I have @tomdonaldson or @andamian gives a thumbs up, too.

However, I would like to cut it up into two PRs, will cherry-pick you second commit into a separate PR to backport for a 1.5.3 release, and keep the deprecation for 1.6. 

(I'm happy to do this all as well as fixing the changelog conflict github complains about)

**Comment by msdemlei** [comment]
On Thu, Aug 08, 2024 at 09:48:40AM -0700, Brigitta Sipőcz wrote:
> (I'm happy to do this all as well as fixing the changelog conflict github complains about)

Thanks!

**Review by tomdonaldson — APPROVED** [review]
This looks good.  Thanks @msdemlei for the changes and @trjaffe and @bsipocz for the discussion.

**Review by andamian — APPROVED** [review]

**Comment by bsipocz** [comment]
Thank you!

**Pull request merged**
