### PR TITLE
Patch for a few issues

### PR DESCRIPTION
**Pull request by andamian**
#272 - @msdemlei - I'm not 100% sure the fix is correct but I couldn't figure out how to make  `message` part of the `errorSummary` class. If you can suggest something better I'll do it.

#270 - I just had to remove the `decode()`. I assume those where there from where `VOTable` was returning the wrong type.

#267 - I've checked and `python-mimeparse` was also in limbo for a while. The functionality we were using from that package was minimal so I've changed the code to not depend on it anymore - pretty small change.

### CODE REVIEW

**Comment by andamian** [comment]
@msdemlei - thanks for the quick review
(a) - good catch. I've added tests for `mime type` (hopefully didn't go overboard with it :-)). The error is now a generic `ValueError` - Don't think a special error would add any value.
(b) - removed the result entry from the failed job
(c) - not sure what you mean here. I couldn't find any reference for `errorSummary` previous to my changes.

**Comment by msdemlei** [comment]
On Fri, Oct 29, 2021 at 11:50:44AM -0700, Adrian wrote:
> (c) - not sure what you mean here. I couldn't find any reference for `errorSummary` previous to my changes.

I was just talking about the code coverage; you see, according to my
review interface, for instance the setter for type on ErrorSummary
(currently on line 417) is never executed by tests.  That seems odd
to me, since the example document does have a type attribute.

If you understand why that is, I'd not object too much (I'm no 100%
coverage zaelot and can live with the occasional untested code path),
but if it's not clear why that doesn't get exercised, then I'd
suspect a bug.

**Comment by andamian** [comment]
> On Fri, Oct 29, 2021 at 11:50:44AM -0700, Adrian wrote: (c) - not sure what you mean here. I couldn't find any reference for `errorSummary` previous to my changes.
> I was just talking about the code coverage; you see, according to my review interface, for instance the setter for type on ErrorSummary (currently on line 417) is never executed by tests. That seems odd to me, since the example document does have a type attribute. If you understand why that is, I'd not object too much (I'm no 100% coverage zaelot and can live with the occasional untested code path), but if it's not clear why that doesn't get exercised, then I'd suspect a bug.

Fixed this in `ErrorSummary` and a few other places - please double-check. I've updated other classes so setting a value goes through the property "setter" so that the value could be properly validated. Let me know you agree or you don't.

**Review by msdemlei — APPROVED** [review]
Looks good to me, except I can't see why you're adding pillow to the dependencies -- is that an accident?

**Comment by andamian** [comment]
> Looks good to me, except I can't see why you're adding pillow to the dependencies -- is that an accident?

It's now testing https://github.com/andamian/pyvo/blob/3c8de6866fd55b587cc03a4e92de4ae679a032b3/pyvo/dal/mimetype.py#L95

I guess the dependency could go into `pip-requirements` except that I see that file being commented out in `tox.ini` for reasons that I don't recall right now.

**Review by tomdonaldson — APPROVED** [review]
Looks good to me.

**Pull request merged**
