### PR TITLE
BUG: fix StringIO uploads

### PR DESCRIPTION
**Pull request by bsipocz**
This is a follow-up to #617 and does fix the issue I see in astroquery.

### CODE REVIEW

**Review by msdemlei — CHANGES_REQUESTED** [review]
I get red lights flashing when I see strings and bytes in parallel.  I have not tried to ascertain that something will be doing the encoding (to utf-8?), and I note that that is not necessarily trivial for XML (which as encoding indicators inside: a charset attribute in the xml declaration, defaulting to utf-8 if not present).

Given that, I'd really love to have some regression test for that.  I'd even bite the bullet and have a remote test for it...

Or is there a simple way to see that the byte/str mix here is unproblematic in this particular context?

**Comment by bsipocz** [comment]
My take on this is that in case of streams we just pass along what we got already on the class instance. Whether that was provided by the user or went through some validation is a separate question. 

That being said, I'm happy to add the tap upload test from astroquery as this one smoked the issue out: https://github.com/astropy/astroquery/blob/main/astroquery/alma/tests/test_alma_remote.py#L566

**Comment by andamian** [comment]
That remote test passes for both `BytesIO` and `StringIO` so I assume that `requests` encodes the string automatically. If `requests` users expect this to work, I see no reason for us to restrict it.

**Review by msdemlei — APPROVED** [review]
Ok, I'm happy with Adrian's explanation, and I trust requests will be doing something robust, so let's go.

**Comment by bsipocz** [comment]
I still meant to add more tests (practically moving or copying the one from astroquery), but it slipped off the radar.

**Pull request merged**
