### PR TITLE
MNT: Replace master with main

### PR DESCRIPTION
**Pull request by pllim**
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.

This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

This is part of #252

### CODE REVIEW

**Comment by pllim** [comment]
Does depend on ci-helpers renaming.

**Comment by bsipocz** [comment]
I've rebased this, and it should be ready to go now -- merging should coincide with changing the settings on the repo though.

**Review by tomdonaldson — APPROVED** [review]
This looks good. Thanks for doing this!

**Comment by bsipocz** [comment]
Thanks @pllim 

And now I go ahead and update the repo settings. Long term we should think about having the "pyvo maintainers" group have admin access to have the ability to edit the repo settings and do the release without interactions from the devops team. Opting in to more branch protection would provide enough safeguard against accidental pushes to the main branch, etc.

**Pull request merged**
