### PR TITLE
MAINT: remove the usage of the astropy TestRunner

### PR DESCRIPTION
**Pull request by bsipocz**
This is to address #604 as well as the upstream plans of actually deprecating the TestRunner.

We haven't really advertised the `pyvo.test()` functionality anywhere, so I would be OK with including this in a bugfix release in the coming few weeks, if that is something you would find helpful @ManonMarchand

### CODE REVIEW

**Review by pllim — APPROVED** [review]
LGTM. Nice to not have to keep a duplicate `conftest.py` any longer. Thanks!

**Comment by bsipocz** [comment]
> Nice to not have to keep a duplicate conftest.py any longer

Yeap, those got me confused several times, and there are still some inconsistencies. E.g Larry kept the one in the photutils directory, though the one there seems to have the comments that it was required by the TestRunner and not by pytest.

Anyway, this layout seems to work both locally with `pytest -P` as well as in tox, so I would just keep it.

**Comment by pllim** [comment]
Not sure if "online tests" job failures are related.

Also, now you don't need the test runner, you can even move all the tests out of package dir if you want.

**Comment by bsipocz** [comment]
Test failures are unrelated, something is off at CADC atm.

> Also, now you don't need the test runner, you can even move all the tests out of package dir if you want.

No, I really don't want to move them out and really don't want to move to a `src/` directory structure, I think there is value keeping tests close to the code. I would only consider changing this if @ManonMarchand browser work explicitly require it.

**Comment by ManonMarchand** [comment]
It works on my side, and if you think that this won't affect the users, getting it in a bugfix release would be welcome

PS: these browser-running python instances are awesome for workshops, maybe I can show you at the IVOA if you're interested? We already have a cds jupyterlite instance with working astroquery examples here [(see notebook 1, even if it needs way more text)](https://cds-astro.github.io/jupyterlite/lab/index.html). It'd be nice to also be able to showcase pyvo

**Review by ManonMarchand — APPROVED** [review]

**Comment by bsipocz** [comment]
Yes, I don't expect any user level issues as we haven't advertized it, and anyway, that usage is underused in the wider astropy ecosystem, too.


PS: I'm very much interested in your browser experience! I'm familiar with the interactive documentation approaches that are happening in the wider scientific python ecosystem, and we are thinking about interactive tutorials, too, but none of those got to the point of applicability on the astroquery/pyvo/navo levels.

**Pull request merged**
