### PR TITLE
Travis job to release to PyPI

### PR DESCRIPTION
**Pull request by andamian**
#181 

The idea is to reduce the releasing of a new version of `pypi` to creating a release in github, with Travis taking care of PyPI publishing. The only requirement is that the `astropy/pyvo` in Travis is configured with the TWINE_PASSWORD environment variable. Although Travis has some safeguards around secret environment variables (https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings) it could be seen as lowering the security bar. @bsipocz has `astropy` org tried/discussed this before? We probably need their agreement.

For a new release, just create a new `github` release in `pyvo` with the label matching the version number. Note that the label needs to match the version number of the `setup.cfg` file in order for the release task to complete successfully.

The mechanism could be used to push to anaconda as well. I'm just not familiar with that process.

Bonus: this also publishes the wheel to address #228 

@cbanek @funbaker @msdemlei or others - please feel free to comment.

### CODE REVIEW

**Comment by bsipocz** [comment]
@andamian - astroquery is doing deployment directly to PyPI (without tagging it to github), so there is no need for twine passwd, etc.

If you would want to do it with a different method, currently @eteq and I have access to set deploy keys/webhooks/etc for pyvo (another action item would be to promote you with admin access, I don't know who can make that decision though).

**Comment by andamian** [comment]
> @andamian - astroquery is doing deployment directly to PyPI (without tagging it to github), so there is no need for twine passwd, etc.
> 
> If you would want to do it with a different method, currently @eteq and I have access to set deploy keys/webhooks/etc for pyvo (another action item would be to promote you with admin access, I don't know who can make that decision though).

I'm obviously not very familiar with the releases. @cbanek has been handled it and my understanding was that it's currently not a very simple process (but I could be wrong). This PR is just an attempt to streamline it and allow any of the maintainers to handle releases.

**Comment by bsipocz** [comment]
In my experience the heavy lifting is done before the tagging (all the cleanup, etc), so generating the sdist and twine upload from there on is the easier part of the process. If you can streamline and partly automate the prior steps then doing the later bits. Anyway,  have a look at the astroquery setup, as I'm certain that can be adjusted to work with a tag/new branch rather than master, and all without the involving twine and passwords.

**Comment by cbanek** [comment]
I like the idea of having the releases be automated, at least the part that does the pushing to the world.  The last time, I was added to the pyvo pypi (say that 3 times fast), but I don't have the ability to manage to add someone else.

It seems like looking at astroquery's travis file, there is a way to use a pypi provider, but that still uses a secret for the account.  That seems like it would replace the publish script.  I guess the provider does something good with the version tagging and figuring it out?

I'm fine with using more Travis special sauce, but it seems like either way we need help with setting the secret or using it?  I'm a bit unsure what the next steps are.

I think releasing on a tag is fine for me, how does astroquery manage the different versions?  Do the new commit versions that aren't on a major tag also get released all the way?  (and how does that interact with version numbers?)

**Comment by andamian** [comment]
@bsipocz I can adapt the `astroquery` deploy model which works in a similar manner. `pyvo` does not have that many releases, hence the idea of tagging the release which I believe is already part of the `pyvo` release process (https://github.com/astropy/pyvo/blob/master/RELEASE.rst). The `github` release feature  just identifies the commit, packages its content and tags it. The tag then triggers the deploy.

**Comment by pllim** [comment]
I don't think this is possible anymore. But you might want to consider Azure Pipeline or GitHub Actions. `astropy` uses Azure Pipelines.

**Pull request closed without merging**
