### PR TITLE
Switching to use system six 

### PR DESCRIPTION
**Pull request by bsipocz**
rather than astropy bundled to keep compatibility

this is not strictly necessary, but an easy sed fix to keep forward compatibility with future astropy.

### CODE REVIEW

**Comment by cbanek** [comment]
Okay I'm all about this change, although I'm wondering if this covers everything?  There's no change to the setup.py to require six, do we need to do that as well?  It seems like you're using the environment variable to help set that up.

This just reminds me that I've seen sometimes where it says six isn't installed, and I did a little bit of digging and it looks like pyvo/dal/mimetype.py already does the import six the way you are changing the other files to (which again, seems good).

**Comment by bsipocz** [comment]
Note that the test setup doesn't rely on dependencies in setup.py, and with `six` we silently assume that people have it installed anyway. But I'm all for being more explicit.

**Comment by cbanek** [comment]
Okay, I wasn't sure about the silently assuming things.  I love virtualenvironments and make them often, especially for testing, so I tend to notice those things.  I'll take it and update the setup.py in another commit.

**Comment by bsipocz** [comment]
Commit is added and also rebased to see whether everything is all green.

**Comment by cbanek** [comment]
Ah fantastic, thanks.  I'll just wait for the tests to run and make sure it's the same ol' expected test errors.

**Comment by cbanek** [comment]
Same expected failure, so we're taking it.

**Pull request merged**
